name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login --username "${{secrets.DOCKER_USERNAME}}" --password-stdin docker.io
    - name: Build Image
      run: make && make tag
    - name: Push Image
      run: make push
 
