name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/docker/login@master
      with: 
        - secrets: ["DOCKER_USERNAME", "DOCKER_PASSWORD"]
    - name: Build Image
      run: make && make tag
    - name: Push Image
      run: make push
 
